services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Gmartino\BreadcrumbLabelsUid\:
    resource: '../Classes/*'

  Gmartino\BreadcrumbLabelsUid\Breadcrumb\RecordUidBreadcrumbProvider:
    tags:
      - name: backend.breadcrumb.provider
